/* Load this script using conditional IE comments if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icomoon\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-marker' : '&#xe000;',
			'icon-home' : '&#xe001;',
			'icon-pencil' : '&#xe002;',
			'icon-droplet' : '&#xe003;',
			'icon-image' : '&#xe004;',
			'icon-expand' : '&#xe005;',
			'icon-contract' : '&#xe006;',
			'icon-key' : '&#xe007;',
			'icon-wrench' : '&#xe008;',
			'icon-settings' : '&#xe009;',
			'icon-cog' : '&#xe00a;',
			'icon-pie' : '&#xe00b;',
			'icon-stats' : '&#xe00c;',
			'icon-bars' : '&#xe00d;',
			'icon-bars-2' : '&#xe00e;',
			'icon-remove' : '&#xe00f;',
			'icon-warning' : '&#xe010;',
			'icon-notification' : '&#xe011;',
			'icon-question' : '&#xe012;',
			'icon-info' : '&#xe013;',
			'icon-blocked' : '&#xe014;',
			'icon-cancel-circle' : '&#xe015;',
			'icon-checkmark-circle' : '&#xe016;',
			'icon-spam' : '&#xe017;',
			'icon-close' : '&#xe018;',
			'icon-checkmark' : '&#xe019;',
			'icon-minus' : '&#xe01a;',
			'icon-plus' : '&#xe01b;',
			'icon-play' : '&#xe01c;',
			'icon-share' : '&#xe01d;',
			'icon-file-pdf' : '&#xe01e;',
			'icon-file-word' : '&#xe01f;',
			'icon-file-excel' : '&#xe020;',
			'icon-file-xml' : '&#xe021;',
			'icon-quill' : '&#xe022;',
			'icon-switch' : '&#xe023;',
			'icon-user' : '&#xe024;',
			'icon-comment' : '&#xe025;',
			'icon-menu' : '&#xe026;',
			'icon-earth' : '&#xe027;',
			'icon-star' : '&#xe028;',
			'icon-play-2' : '&#xe029;',
			'icon-connection' : '&#xe02a;',
			'icon-book' : '&#xe02b;',
			'icon-file' : '&#xe02c;',
			'icon-copy' : '&#xe02d;',
			'icon-folder-open' : '&#xe02e;',
			'icon-history' : '&#xe02f;',
			'icon-pushpin' : '&#xe030;',
			'icon-envelop' : '&#xe031;',
			'icon-address-book' : '&#xe032;',
			'icon-phone' : '&#xe033;',
			'icon-calculate' : '&#xe034;',
			'icon-credit' : '&#xe035;',
			'icon-cart' : '&#xe036;',
			'icon-tag' : '&#xe037;',
			'icon-clock' : '&#xe038;',
			'icon-alarm' : '&#xe039;',
			'icon-calendar' : '&#xe03a;',
			'icon-print' : '&#xe03b;',
			'icon-keyboard' : '&#xe03c;',
			'icon-screen' : '&#xe03d;',
			'icon-mobile' : '&#xe03e;',
			'icon-disk' : '&#xe03f;',
			'icon-undo' : '&#xe040;',
			'icon-undo-2' : '&#xe041;',
			'icon-bubble' : '&#xe042;',
			'icon-bubbles' : '&#xe043;',
			'icon-user-2' : '&#xe044;',
			'icon-user-3' : '&#xe045;',
			'icon-quotes-left' : '&#xe046;',
			'icon-spinner' : '&#xe047;',
			'icon-search' : '&#xe048;',
			'icon-zoom-in' : '&#xe049;',
			'icon-zoom-out' : '&#xe04a;',
			'icon-lock' : '&#xe04b;',
			'icon-unlocked' : '&#xe04c;',
			'icon-cogs' : '&#xe04d;',
			'icon-bug' : '&#xe04e;',
			'icon-upload' : '&#xe04f;',
			'icon-download' : '&#xe050;',
			'icon-cloud-download' : '&#xe051;',
			'icon-tree' : '&#xe052;',
			'icon-signup' : '&#xe053;',
			'icon-remove-2' : '&#xe054;',
			'icon-link' : '&#xe055;',
			'icon-flag' : '&#xe056;',
			'icon-attachment' : '&#xe057;',
			'icon-heart' : '&#xe058;',
			'icon-thumbs-up' : '&#xe059;',
			'icon-smiley' : '&#xe05a;',
			'icon-sad' : '&#xe05b;',
			'icon-info-2' : '&#xe05c;',
			'icon-stop' : '&#xe05d;',
			'icon-pause' : '&#xe05e;',
			'icon-backward' : '&#xe05f;',
			'icon-forward' : '&#xe060;',
			'icon-first' : '&#xe061;',
			'icon-last' : '&#xe062;',
			'icon-previous' : '&#xe063;',
			'icon-next' : '&#xe064;',
			'icon-checkbox-checked' : '&#xe065;',
			'icon-checkbox-unchecked' : '&#xe066;',
			'icon-checkbox-partial' : '&#xe067;',
			'icon-radio-checked' : '&#xe068;',
			'icon-radio-unchecked' : '&#xe069;',
			'icon-table' : '&#xe06a;',
			'icon-insert-template' : '&#xe06b;',
			'icon-code' : '&#xe06c;',
			'icon-new-tab' : '&#xe06d;',
			'icon-android' : '&#xe06e;',
			'icon-windows8' : '&#xe06f;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};